package biz.shujutech.payroll;

import biz.shujutech.base.Connection;
import biz.shujutech.bznes.Money;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;

public class MsiaSocsoCalculator {
	class SocsoRow {
		double wageUpTo;
		double catFirstEmployer;
		double catFirstEmployee;
		double catTwoEmployer;
	}

	public static MsiaSocsoCalculator SocsoTable = null;
	List<SocsoRow> socsoSchedule = 	new CopyOnWriteArrayList();

	public void parseToTable() {
		Document doc = Jsoup.parse(StrHtmlTable, "", Parser.xmlParser());
		Element table = doc.select("table").get(0); //select the first table.
		Elements rows = table.select("tr");
		this.socsoSchedule.clear();
		for (int cntr = 3; cntr < rows.size(); cntr++) { //first row is the col names so skip it.
			Element row = rows.get(cntr);
			Elements cols = row.select("td");

			SocsoRow socsoRow = new SocsoRow();
			socsoRow.wageUpTo = Double.parseDouble(GetLastNumber(cols.get(1).text()));
			socsoRow.catFirstEmployer = Double.parseDouble(GetNumberOnly(cols.get(2).text()));
			socsoRow.catFirstEmployee = Double.parseDouble(GetNumberOnly(cols.get(3).text()));
			socsoRow.catTwoEmployer = Double.parseDouble(GetNumberOnly(cols.get(5).text()));
			socsoSchedule.add(socsoRow);
		}
	}

	public List<Double> getSocsoAmount(Money aWage) throws Exception {
		if (this.socsoSchedule.isEmpty()) {
			this.parseToTable();
		}

		List<Double> result = new CopyOnWriteArrayList<>();
		Double wage = aWage.getValueDouble();
		int exceed2900 = socsoSchedule.size() - 1;
		for (int cntr = 0; cntr < socsoSchedule.size(); cntr++) {
			SocsoRow socsoRow = socsoSchedule.get(cntr);
			if (wage < socsoRow.wageUpTo || cntr == exceed2900) {
				result.add(socsoRow.catFirstEmployer);
				result.add(socsoRow.catFirstEmployee);
				result.add(socsoRow.catTwoEmployer);
				break;
			}
		}
		if (result.isEmpty()) {
			result.add(0D);
			result.add(0D);
			result.add(0D);
		}
		return(result);
	}

	public static String GetNumberOnly(String aStr) {
		String result = "";
		for (int cntr = 0; cntr < aStr.length(); cntr++) {
			if ((aStr.charAt(cntr) >= '0' && aStr.charAt(cntr) <= '9') || aStr.charAt(cntr) == '.') {
				result += aStr.charAt(cntr);
			}
		}
		return(result);
	}

	public static String GetLastNumber(String aStr) {
		boolean findSpace = false;
		int cntr = aStr.length() - 1;
		for (;cntr >= 0; cntr--) {
			if (aStr.charAt(cntr) >= '0' && aStr.charAt(cntr) <= '9') {
				findSpace = true;
			}
			if (findSpace == true) {
				if (aStr.charAt(cntr) == ' ') {
					break;
				}
			}
		}

		if (cntr == aStr.length() - 1) {
			cntr = 0;
		}

		String result = aStr.substring(cntr);
		result = result.substring(result.indexOf(' '));
		result = GetNumberOnly(result);
		return(result);
	}

	public static Money GetSocsoableAmount(Connection aConn, SalarySlip aPayslip) throws Exception {
		return(SalarySlipMalaysia.GetAffectedAmount(aConn, aPayslip, SalarySlipMalaysia.AFFECT_SOCSO));
	}

	public static String GetSocsoAmount(Connection aConn, SalarySlip aPayslip, Money aBasicSalary, Double aAge
	, Boolean aIsNewMember, Double aWageBeforeInvalidity , Money aBossContribution, Money aWorkerContribution) throws Exception {
		/*
		Money totalSocsoEarning = (Money) ObjectBase.CreateObject(aConn, Money.class);
		totalSocsoEarning.setValue(aBasicSalary.getCurrencyCode(), 0D);

		// total up the wages as defined by Socso
		aPayslip.getFieldObjectBox(biz.shujutech.payroll.SalarySlip.Earnings).resetIterator();
		while (aPayslip.getFieldObjectBox(biz.shujutech.payroll.SalarySlip.Earnings).hasNext(aConn)) {
			SalaryTransaction eachEarning = (SalaryTransaction) aPayslip.getFieldObjectBox(biz.shujutech.payroll.SalarySlip.Earnings).getNext();
			if (eachEarning.getDescr().toLowerCase().contains("salary")
			|| eachEarning.getDescr().toLowerCase().contains("overtime") 
			|| eachEarning.getDescr().toLowerCase().contains("commission")
			|| eachEarning.getDescr().toLowerCase().contains("leave")
			|| eachEarning.getDescr().toLowerCase().contains("allowance")
			|| eachEarning.getDescr().toLowerCase().contains("cola")
			|| eachEarning.getDescr().toLowerCase().contains("service")
			) 
			{
				totalSocsoEarning.addAmount(eachEarning.getAmount());
			}
		}
		*/
		Money totalSocsoEarning = GetSocsoableAmount(aConn, aPayslip);

		if (SocsoTable == null) {
			SocsoTable = new MsiaSocsoCalculator();
			SocsoTable.parseToTable();
		}
		List<Double> socsoAry = SocsoTable.getSocsoAmount(totalSocsoEarning); // get the employee portion from the Socso table
		Double dblSocsoEmployer = socsoAry.get(0);
		Double dblSocsoEmployee = socsoAry.get(1);
		Double dblSocsoCatTwoEmployer = socsoAry.get(2);

		// determine socso category, http://www.perkeso.gov.my/en/social-security-protection/employer-employee-eligibilty/contribution.html
		String whatCategory = "First Category";
		if (aAge >= 60.0) {
			whatCategory = "Second Category";
		} else if (aAge > 55 && aIsNewMember) {
			whatCategory = "Second Category";
		} else if (aWageBeforeInvalidity != null) {
			if (totalSocsoEarning.getValueDouble() > (0.33333 * aWageBeforeInvalidity)) {
				whatCategory = "Second Category";
			}
		}

		if (whatCategory.equals("First Category")) {
			aBossContribution.setValue(totalSocsoEarning.getCurrencyCode(), dblSocsoEmployer);
			aWorkerContribution.setValue(totalSocsoEarning.getCurrencyCode(), dblSocsoEmployee);
		} else {
			aBossContribution.setValue(totalSocsoEarning.getCurrencyCode(), 0.0D);
			aBossContribution.setValue(totalSocsoEarning.getCurrencyCode(), dblSocsoCatTwoEmployer);
		}

		return(whatCategory);
	}

	public static void main(String[] argv) {
		MsiaSocsoCalculator socsoTable = new MsiaSocsoCalculator();
		socsoTable.parseToTable();
	}

	// https://www.perkeso.gov.my/index.php/ms/perkhidmatan-kami/majikan-pekerja/kelayakan-majikan-pekerja/kadar-caruman
	public static String StrHtmlTable = "<table class=\"gridgridtable\">"
	+ "<tbody>"
	+ "<tr><th colspan=\"6\" style=\"background-color: #c0c0c0; text-align: center;\" nowrap=\"nowrap\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><span style=\"font-size: 10pt;\"><strong>KADAR CARUMAN</strong></span></p>"
	+ "</th></tr>"
	+ "<tr style=\"height: 25.3pt;\"><th rowspan=\"2\" style=\"text-align: center; background-color: #9acd32;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Bil</strong></p>"
	+ "</th><th rowspan=\"2\" style=\"text-align: center; background-color: #9acd32;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Gaji Bulanan</strong></p>"
	+ "</th><th colspan=\"3\" style=\"text-align: center; background-color: #ffff99;\">"
	+ "<p style=\"line-height: normal; margin-bottom: 0pt;\"><strong>Jenis Pertama <br>(Skim Bencana Pekerjaan dan <br>Skim Keilatan)</strong></p>"
	+ "</th><th style=\"text-align: center; background-color: #55eeee;\">"
	+ "<p style=\"line-height: normal; margin-bottom: 0pt;\"><strong>Jenis Kedua <br>(Skim Bencana </strong></p>"
	+ "<p style=\"line-height: normal; margin-bottom: 0pt;\"><strong>Pekerjaan)<br><br></strong></p>"
	+ "</th></tr>"
	+ "<tr><th style=\"text-align: center; background-color: #ffff99;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Syer Majikan </strong></p>"
	+ "</th><th style=\"text-align: center; background-color: #ffff99;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Syer Pekerja</strong></p>"
	+ "</th><th style=\"text-align: center; background-color: #ffff99;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Jumlah Caruman</strong></p>"
	+ "</th><th style=\"background-color: #55eeee;\">"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Jumlah Caruman </strong></p>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Oleh Majikan </strong></p>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\"><strong>Sahaja </strong></p>"
	+ "</th></tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">1.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Gaji hingga RM 30</p>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">&nbsp;</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">40 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">10 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">50 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">30 sen</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">2.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM30 tetapi tidak melebihi RM50</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">70 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">20 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">90 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">50 sen</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">3.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM50 tetapi tidak melebihi RM70</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">30 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">80 sen</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">4.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM70 tetapi tidak melebihi RM100</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.50</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">40 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">5.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM100 tetapi tidak melebihi RM140</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">60 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.70</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.50</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">6.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM140 tetapi tidak melebihi RM200</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.95</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">85 sen</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM3.80</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">7.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM200 tetapi tidak melebihi RM300</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM4.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM5.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM3.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">8.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM300 tetapi tidak melebihi RM400</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM6.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM1.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM7.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM4.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">9.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM400 tetapi tidak melebihi RM500</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM7.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM10.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM5.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 24.75pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">10.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM500 tetapi tidak melebihi RM600</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM9.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM2.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM12.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM6.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">11.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM600 tetapi tidak melebihi RM700</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM11.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM3.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM14.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM8.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">12.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM700 tetapi tidak melebihi RM800</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM13.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM3.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM16.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM9.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">13.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM800 tetapi tidak melebihi RM900</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM14.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM4.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM19.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM10.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">14.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM900 tetapi tidak melebihi RM1,000</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM16.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM4.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM21.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM11.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">15.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,000 tetapi tidak melebihi RM1,100</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM18.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM5.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM23.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM13.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">16.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,100 tetapi tidak melebihi RM1,200</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM20.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM5.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM25.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM14.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">17.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,200 tetapi tidak melebihi RM1,300</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM21.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM6.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM28.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM15.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">18.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,300 tetapi tidak melebihi RM1,400</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM23.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM6.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM30.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM16.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">19.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,400 tetapi tidak melebihi RM1,500</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM25.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM7.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM32.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM18.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">20.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,500 tetapi tidak melebihi RM1,600</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM27.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM7.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM34.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM19.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">21.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,600 tetapi tidak melebihi RM1,700</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM28.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM8.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM37.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM20.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">22.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,700 tetapi tidak melebihi RM1,800</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM30.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM8.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM39.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM21.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">23.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,800 tetapi tidak melebihi RM1,900</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM32.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM9.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM41.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM23.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">24.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM1,900 tetapi tidak melebihi RM2,000</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM34.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM9.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM43.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM24.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">25.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,000 tetapi tidak melebihi RM2,100</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM35.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM10.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM46.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM25.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">26.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,100 tetapi tidak melebihi RM2,200</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM37.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM10.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM48.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM26.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 24.75pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">27.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,200 tetapi tidak melebihi RM2,300</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM39.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM11.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM50.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM28.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">28.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,300 tetapi tidak melebihi RM2,400</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM41.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM11.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM52.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM29.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">29.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,400 tetapi tidak melebihi RM2,500</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM42.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM12.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM55.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM30.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">30.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,500 tetapi tidak melebihi RM2,600</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM44.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM12.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM57.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM31.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">31.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,600 tetapi tidak melebihi RM2,700</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM46.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM13.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM59.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM33.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">32.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,700 tetapi tidak melebihi RM2,800</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM48.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM13.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM61.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM34.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr style=\"height: 25.5pt;\">"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">33.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,800 tetapi tidak melebihi RM2,900</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM49.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM14.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM64.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM35.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">34.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM2,900 tetapi tidak melebihi RM3,000</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM51.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM14.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM66.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM36.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">35.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,000 tetapi tidak melebihi RM3,100</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM53.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM15.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM68.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM38.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">36.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,100 tetapi tidak melebihi RM3,200</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM55.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM15.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM70.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM39.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">37.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,200 tetapi tidak melebihi RM3,300</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM56.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM16.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM73.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM40.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">38.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,300 tetapi tidak melebihi RM3,400</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM58.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM16.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM75.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM41.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">39.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,400 tetapi tidak melebihi RM3,500</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM60.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM17.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM77.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM43.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">40.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,500 tetapi tidak melebihi RM3,600</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM62.15</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM17.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM79.90</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM44.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">41.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,600 tetapi tidak melebihi RM3,700</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM63.85</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM18.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM82.10</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM45.60</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">42.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,700 tetapi tidak melebihi RM3,800</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM65.65</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM18.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM84.40</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM46.90</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">43.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,800 tetapi tidak melebihi RM3,900</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM67.35</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM19.25</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM86.60</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM48.10</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">44.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM3,900 tetapi tidak melebihi RM4,000</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM69.05</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM19.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM88.80</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM49.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "<tr>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">45.</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">Apabila gaji melebihi RM4,000</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM69.05</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM19.75</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM88.80</p>"
	+ "</td>"
	+ "<td>"
	+ "<p style=\"margin-bottom: 0.0001pt; line-height: normal;\">RM49.40</p>"
	+ "</td>"
	+ "</tr>"
	+ "</tbody>"
	+ "</table>";
	
}
	
	